************* Module app.src.connection_utility
app/src/connection_utility.py:24:4: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
app/src/connection_utility.py:22:0: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
app/src/connection_utility.py:46:0: C0116: Missing function or method docstring (missing-function-docstring)
app/src/connection_utility.py:47:4: W0621: Redefining name 'connections' from outer scope (line 89) (redefined-outer-name)
app/src/connection_utility.py:49:13: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
app/src/connection_utility.py:55:0: C0116: Missing function or method docstring (missing-function-docstring)
app/src/connection_utility.py:55:22: W0621: Redefining name 'connections' from outer scope (line 89) (redefined-outer-name)
app/src/connection_utility.py:72:12: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
************* Module app.src.cli
app/src/cli.py:54:0: C0301: Line too long (125/100) (line-too-long)
app/src/cli.py:97:0: C0305: Trailing newlines (trailing-newlines)
app/src/cli.py:83:8: C0415: Import outside toplevel (main_call.return_engine) (import-outside-toplevel)
app/src/cli.py:90:15: W0718: Catching too general exception Exception (broad-exception-caught)
************* Module app.src.connection_manager
app/src/connection_manager.py:154:0: C0305: Trailing newlines (trailing-newlines)
app/src/connection_manager.py:28:13: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
app/src/connection_manager.py:35:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
app/src/connection_manager.py:91:12: C0103: Variable name "ConnType" doesn't conform to snake_case naming style (invalid-name)
app/src/connection_manager.py:92:32: C0321: More than one statement on a single line (multiple-statements)
app/src/connection_manager.py:92:32: C0103: Variable name "ConnType" doesn't conform to snake_case naming style (invalid-name)
app/src/connection_manager.py:93:34: C0321: More than one statement on a single line (multiple-statements)
app/src/connection_manager.py:93:34: C0103: Variable name "ConnType" doesn't conform to snake_case naming style (invalid-name)
app/src/connection_manager.py:94:34: C0321: More than one statement on a single line (multiple-statements)
app/src/connection_manager.py:94:34: C0103: Variable name "ConnType" doesn't conform to snake_case naming style (invalid-name)
app/src/connection_manager.py:95:34: C0321: More than one statement on a single line (multiple-statements)
app/src/connection_manager.py:95:34: C0103: Variable name "ConnType" doesn't conform to snake_case naming style (invalid-name)
app/src/connection_manager.py:82:0: R0912: Too many branches (17/12) (too-many-branches)
app/src/connection_manager.py:82:0: R0915: Too many statements (62/50) (too-many-statements)
************* Module app.src.main_call
app/src/main_call.py:46:36: C0303: Trailing whitespace (trailing-whitespace)
app/src/main_call.py:47:55: C0303: Trailing whitespace (trailing-whitespace)
app/src/main_call.py:54:70: C0303: Trailing whitespace (trailing-whitespace)
app/src/main_call.py:55:64: C0303: Trailing whitespace (trailing-whitespace)
app/src/main_call.py:59:0: C0305: Trailing newlines (trailing-newlines)
app/src/main_call.py:3:0: E0401: Unable to import 'pandas' (import-error)
app/src/main_call.py:4:0: E0401: Unable to import 'yaml' (import-error)
app/src/main_call.py:7:0: E0401: Unable to import 'sqlalchemy' (import-error)
app/src/main_call.py:27:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
app/src/main_call.py:31:4: C0103: Variable name "CONNECTION_STRING" doesn't conform to snake_case naming style (invalid-name)
app/src/main_call.py:46:4: C0103: Constant name "string" doesn't conform to UPPER_CASE naming style (invalid-name)
app/src/main_call.py:7:0: C0411: third party import "sqlalchemy.create_engine" should be placed before local import "connection_utility.make_string" (wrong-import-order)
app/src/main_call.py:1:0: R0801: Similar lines in 2 files
==app.src.connection_manager:[8:26]
==app.src.connection_utility:[6:23]
conn_home = os.getenv('conn_home')
# print(f"conn_home: {conn_home}")

# Define the path for the connections file
connections_file = os.path.join(conn_home, 'connections.yaml')
# print(f"connections_file: {connections_file}")

# Check if the file exists

if os.path.exists(connections_file):
    # print("File exists.")
    pass #pass is for doing nothing
else:
    print("File does not exist.")

# Function to load the connections from the file
def load_connections():
    """Load connections from the YAML file.""" (duplicate-code)

-----------------------------------
Your code has been rated at 7.95/10

